package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/basit/fileshare-backend/graph/model"
)

// FileStats is the resolver for the fileStats field.
func (r *queryResolver) FileStats(ctx context.Context, fileID string) (*model.FileStats, error) {
	panic(fmt.Errorf("not implemented: FileStats - fileStats"))
}
