// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID              string `json:"id"`
	Email           string `json:"email"`
	CreatedAt       string `json:"createdAt"`
	DownloadAlerts  bool   `json:"downloadAlerts"`
	ExpiryReminders bool   `json:"expiryReminders"`
}

type UserStats struct {
	TotalFiles     int32  `json:"totalFiles"`
	TotalDownloads int32  `json:"totalDownloads"`
	StorageUsed    string `json:"storageUsed"`
}
